name: UI/Design Improvement
description: Suggest improvements to the website's appearance or user experience
title: "[UI/UX]: "
labels: ["enhancement", "ui/ux"]
body:
  - type: markdown
    attributes:
      value: |
        ## Suggest a UI/UX Improvement
        Use this form to suggest improvements to how the website looks or how easy it is to use.
        
  - type: dropdown
    id: area
    attributes:
      label: Which area should be improved?
      description: Which part of the website would you like to enhance?
      options:
        - Colors and theme
        - Layout and spacing
        - Buttons and controls
        - Text and fonts
        - Images and icons
        - Mobile/responsive design
        - Animations and effects
        - Overall user experience
        - Multiple areas
    validations:
      required: true
      
  - type: textarea
    id: current-state
    attributes:
      label: Current Appearance/Experience
      description: Describe how it looks or works now
      placeholder: "Describe the current state (e.g., 'The buttons are blue and hard to see')"
    validations:
      required: true
      
  - type: textarea
    id: desired-improvement
    attributes:
      label: Desired Improvement
      description: What would you like to change or improve?
      placeholder: "Describe your suggestion (e.g., 'Make buttons lime green to match school colors')"
    validations:
      required: true
      
  - type: textarea
    id: reason
    attributes:
      label: Why this improvement?
      description: Why would this be better?
      placeholder: "Explain the benefit (e.g., 'Better matches school branding and easier to see')"
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this improvement?
      options:
        - High - Very important, impacts many users
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true
      
  - type: textarea
    id: examples
    attributes:
      label: Examples or References (Optional)
      description: Link to examples or describe similar designs you like
      placeholder: "Share links to examples or describe what you have in mind"
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        ---
        ### Acceptance Criteria
        - The suggested improvement should be implemented
        - The design should maintain consistency with the rest of the website
        - The changes should work well on different screen sizes (mobile, tablet, desktop)
        - The improvement should enhance usability or visual appeal
        
        ### Implementation Hints
        - **Styling**: All CSS is in `src/static/styles.css`
        - **HTML structure**: Main page is `src/static/index.html`
        - **School colors**: White and lime green (as mentioned in requirements)
        - **Current theme**: Supports dark mode toggle
        - **Mascots**: Using Octodex images from https://octodex.github.com/
        - **JavaScript**: Frontend logic is in `src/static/app.js`
        - **Keep it simple**: Non-technical staff should be able to maintain the code
